apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  labels:
    app: wisecow
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # External port (what the Ingress/browser hits)
      targetPort: 4499  # Internal port (what wisecow.sh listens on)
  type: ClusterIP       # Internal only - Ingress will handle external access
